@startuml
skinparam ClassAttributeIconStyle none

' ---------------------------------
' Kelas Model (Tanpa Metode)
' ---------------------------------
class User {
  + id_pengguna
  + nama : string
  + email : string
  - password : string
  + nomor_telepon : string
  + alamat : string
  + foto_profil : string
  + role : string
}

class Produk {
  + id_produk : Produk 
  + nama_produk : string
  + kategori_produk : string
  + deskripsi_produk : string
  + berat_produk : float
  + harga_produk : float
  + stok_produk : int
  + foto_produk : string
  + status_produk : string
}

class Pesanan {
  + id_pesanan : Pesanan 
  + id_pembeli : User 
  + alamat_pengiriman : string
  + status_pemesanan : string
  + waktu_pemesanan : DateTime
}

class DetailPesanan {
  + id_detail_pesanan : DetailPesanan 
  + id_pesanan : Pesanan 
  + id_produk : Produk 
  + kuantitas_produk : int
  + harga_produk_tersimpan : float
}

class Komplain {
  + id_komplain : Komplain 
  + id_pesanan : Pesanan 
  + judul_komplain : string
  + deskripsi_komplain : string
  + bukti_komplain : string
  + tanggal_pengaduan : DateTime
  + status_komplain : string
}

class Berita {
  + id_berita : Berita 
  + id_penulis : User
  + judul_berita : string
  + isi_berita : text
  + gambar_berita : string
  + tanggal_publikasi : DateTime
}

' sisi pengguna

' auth
class LoginController {
  + masuk(request: Request)
}

class LogoutController {
  + logout(request: Request)
}

class RegisterController {
  + daftarPengguna(request: Request)
}

' profil
class LihatProfilController {
  + ambilProfil(request: Request)
}

class UbahKataSandiController {
  + ubahKataSandi(request: Request)
}

class UbahProfilController {
  + ubahProfil(request: Request)
}

' produk
class LihatProdukController {
  + ambilSemuaProduk(request: Request)
  + ambilProdukTerlaris()
  + ambilDetailProduk(id: int)
  + cariProduk(request: request)

}

' pesanan
class LihatPesananController {
  + ambilDaftarPesanan(request: Request)
  + ambilDetailPesanan(id: int)
}

class TambahPesananController {
  + buatPesanan(request: Request)
}

' pembayaran
class BatalkanPembayaranController {
  + batalkanPesanan(request: Request, id_pesanan: int)
}

class KonfirmasiPembayaranController {
  + perbaruiStatusPembayaran(request: Request, id_pesanan: int)
}

class LihatDetailPembayaranController {
  + ambilDetailPembayaran(request: Request, id_pesanan: int)
}

' komplain
class TambahKomplainController {
  + ajukanKomplain(request: Request, id_pesanan: int)
}

' berita
class LihatBeritaController {
 + ambilDaftarBerita(request: Request)
 + ambilBeritaTerkini(request: Request)
 + ambilDetailBerita(id_berita: int)
}

' sisi admin

' produk
class HapusProdukController {
  + hapusProduk(id: int)
}

class TambahProdukController {
  + tambahProduk(request: Request)
}

class UbahProdukController {
  + ubahProduk(request: Request, id: int)
}

' pesanan
class LihatSemuaPesananController {
  + ambilSemuaPesanan(request: Request)
}

class UbahPesananController {
  + perbaruiStatusPesanan(request: Request, id_pesanan: int)
}

' komplain
class LihatKomplainController {
  + ambilDaftarKomplain(request: Request)
  + ambilDetailKomplain(id_komplain: int)
}

class UbahKomplainController {
  + perbaruiStatusKomplain(request: Request, id_komplain: int)
}

' berita 
class HapusBeritaContoller {
  + hapusBerita(id_berita: int)
}

class TambahBeritaController {
  + tambahBerita(request: Request)
}

class UbahBeritaController {
  + ubahBerita(request: Request, id_berita: int)
}

' ---------------------------------
' Hubungan Model-Model (Asosiasi & Komposisi)
' ---------------------------------
User "1" -- "0..*" Pesanan : adalah_pembeli >
User "1" -- "0..*" Berita : adalah_penulis >

Pesanan "1" *-- "1..*" DetailPesanan : terdiri_dari >
Produk "1" -- "0..*" DetailPesanan : dijual_di >

Pesanan "1" -- "0..1" Komplain : memiliki >

' ---------------------------------
' Hubungan Controller-Model (Dependensi)
' ---------------------------------

'berita admin
HapusBeritaContoller ..> Berita : menggunakan
TambahBeritaController ..> Berita : menggunakan
UbahBeritaController ..> Berita : menggunakan
'berita pembeli
LihatBeritaController ..> Berita : menggunakan

'komplain admin
LihatKomplainController ..> Komplain : menggunakan
UbahKomplainController ..> Komplain : menggunakan
'komplain pembeli
TambahKomplainController ..> Komplain : menggunakan

'pesanan admin
LihatSemuaPesananController ..> Pesanan : menggunakan
UbahPesananController ..> Pesanan : menggunakan
'pesanan pembeli
LihatPesananController ..> Pesanan : menggunakan
TambahPesananController ..> Pesanan : menggunakan

'produk admin
HapusBeritaContoller ..> Produk : menggunakan
TambahProdukController ..> Produk : menggunakan
UbahProdukController ..> Produk : menggunakan
'produk pembeli
LihatProdukController ..> Produk : menggunakan

'auth pembeli
LoginController ..> User : menggunakan
LogoutController ..> User : menggunakan
RegisterController ..> User : menggunakan

'pembayaran
BatalkanPembayaranController ..> Pesanan : menggunakan
KonfirmasiPembayaranController ..> Pesanan : menggunakan
LihatDetailPembayaranController ..> Pesanan : menggunakan

@enduml