@startuml SD-UC-A03_UpdateProfil
title Sequence Diagram UC-A03: Memperbarui Data Profil
skinparam style strictuml

actor Pengguna
boundary HalamanProfil
control UbahProfilController
entity User
database users

activate Pengguna
Pengguna -> HalamanProfil : Klik "Simpan Profil"
activate HalamanProfil

HalamanProfil -> UbahProfilController : ubahProfil($request: Request)
activate UbahProfilController

UbahProfilController -> UbahProfilController : validate($request: Request)
UbahProfilController -> User : $user->update($data: Array)
activate User

User -> users : UPDATE users SET ... WHERE id = $user->id
activate users

users --> User : return(true: Boolean)
deactivate users

User --> UbahProfilController : return(true: Boolean)
deactivate User

UbahProfilController --> HalamanProfil : response($data: Array)
deactivate UbahProfilController

HalamanProfil -> HalamanProfil : authStore.setUser($user)

HalamanProfil -> Pengguna : Tampilkan profil terbaru
deactivate HalamanProfil
deactivate Pengguna

@enduml