@startuml SD-UC-A01_MendaftarAkun
title Sequence Diagram UC-A01: Mendaftar Akun
skinparam style strictuml

actor Pengguna
boundary register
control RegisterController
entity User
database users

activate Pengguna
Pengguna -> register : Mengakses halaman /auth/register
activate register

register -> Pengguna : Tampilkan halaman pendaftaran

Pengguna -> register : Input data registrasi

Pengguna -> register : Klik "Daftar"

register -> RegisterController : daftarPengguna($request: Request)
activate RegisterController

RegisterController -> RegisterController : validate($request: Request)

RegisterController -> User : User::create($request: Request)
activate User

User -> users : INSERT INTO users VALUES (data)
activate users

users --> User : return(user: Users)
deactivate users

User --> RegisterController : return(user: Users)
deactivate User

RegisterController --> register : response($data: Array)
deactivate RegisterController

register -> register : router.push('/auth/login')

register -> Pengguna : Tampilkan halaman login
deactivate register
deactivate Pengguna

@enduml