@startuml SD-UC-A01_MendaftarAkun
title Sequence Diagram UC-A01: Mendaftar dan Membuat Akun
skinparam style strictuml

actor Pengguna
boundary HalamanRegister
control UserController
database user as "user\n(Database)"

box "Sistem Pendaftaran"
    participant HalamanRegister
    participant UserController
end box

activate Pengguna
Pengguna -> HalamanRegister : Mengakses halaman Register
activate HalamanRegister

HalamanRegister -> Pengguna : Tampilkan formulir pendaftaran (Langkah 1)

Pengguna -> HalamanRegister : Mengisi data lengkap (Langkah 2)

Pengguna -> HalamanRegister : Menekan tombol "Daftar Sekarang" (Langkah 3)

HalamanRegister -> UserController : daftarPengguna(Data Register)
activate UserController

UserController -> UserController : Validasi data (Format, Kelengkapan, Keunikan Email) (Langkah 4)

' alt Gagal Validasi (Alternative Flow 4.a)
'     UserController -> HalamanRegister : Tampilkan notifikasi("Pendaftaran Gagal") (Langkah 4.b)
'     HalamanRegister -> Pengguna : Tampilkan notifikasi dan sorot kolom bermasalah
    
'     Pengguna -> HalamanRegister : Memperbaiki data (Langkah 4.c)
    
'     note over Pengguna, HalamanRegister
'         Kembali ke Langkah 3 (Main Flow) / Lanjutkan input
'     end note
' else Validasi Sukses (Langkah 4)
'     UserController -> UserController : HASH Password
'     UserController -> user : Simpan data pengguna baru(Data Hash, Status Aktif) (Langkah 5)
'     activate user
    
'     note over user
'         Simpan akun ke Database
'     end note
    
'     user --> UserController : ID_Pengguna_Baru
'     deactivate user

'     UserController -> HalamanRegister : Tampilkan notifikasi("Pendaftaran Berhasil") (Langkah 6)
'     deactivate UserController
    
'     HalamanRegister -> Pengguna : Menerima notifikasi berhasil (Langkah 7)
'     deactivate HalamanRegister
' end alt
deactivate Pengguna

@enduml