@startuml SD-UC-A04_UbahKataSandi
title Sequence Diagram UC-A04: Mengubah Kata Sandi Akun
skinparam style strictuml

actor Pengguna
boundary HalamanProfil
control UbahKataSandiController
entity User

activate Pengguna
Pengguna -> HalamanProfil : Input password baru
activate HalamanProfil

Pengguna -> HalamanProfil : Klik "Ubah Kata Sandi"

HalamanProfil -> UbahKataSandiController : ubahKataSandi($request: Request)
activate UbahKataSandiController

UbahKataSandiController -> UbahKataSandiController : validate($request: Request)

' Cek Hash Password Lama
UbahKataSandiController -> UbahKataSandiController : Hash::check($request->password: String)

' Hashing Password Baru
UbahKataSandiController -> UbahKataSandiController : Hash::make($request->password_baru: String)

' Update ke Database
UbahKataSandiController -> User : $user->save()
activate User

User --> UbahKataSandiController : return(true: boolean)
deactivate User

UbahKataSandiController --> HalamanProfil : response($data: Array)
deactivate UbahKataSandiController

HalamanProfil -> Pengguna : Tampilkan notifikasi "Password berhasil diubah"
deactivate HalamanProfil
deactivate Pengguna
@enduml