@startuml SD-UC-A02_Login
title Sequence Diagram UC-A02: Masuk ke Akun Pengguna
skinparam style strictuml

actor Pengguna
boundary login
control LoginController
entity User
database users

activate Pengguna
Pengguna -> login : Mengakses halaman /auth/login
activate login

login --> Pengguna : Tampilkan halaman login

Pengguna -> login : Input email dan password

Pengguna -> login : Klik "Masuk"

login -> LoginController : masuk($request: Request)
activate LoginController

LoginController -> LoginController : validate($request)

LoginController -> User : User::where('email': String, $request->email: String )
activate User

User -> users : SELECT * FROM users WHERE email = $request->email LIMIT 1
activate users

users --> User : return(user: Users)
deactivate users

User --> LoginController : return(user: Users)
deactivate User

LoginController --> login : response($data: Array)
deactivate LoginController

login -> login : router.push('/dashboard': String)
login --> Pengguna : Tampilkan halaman dashboard
deactivate login
deactivate Pengguna

@enduml