@startuml SD-UC-A01_MendaftarAkun
title Sequence Diagram UC-A01: Mendaftar Akun
skinparam style strictuml

actor Pengguna
boundary HalamanRegister
control UserController
entity User

activate Pengguna
Pengguna -> HalamanRegister : Mengakses halaman Register
activate HalamanRegister

HalamanRegister -> Pengguna : Tampilkan formulir pendaftaran

Pengguna -> HalamanRegister : Input(Data Registrasi)

Pengguna -> HalamanRegister : Klik "Daftar Sekarang"

HalamanRegister -> UserController : register(request: RegisterRequest)
activate UserController

UserController -> User : validate(request.data)
activate User

UserController -> User : create(request.data)

User --> UserController : user: User
deactivate User

UserController --> HalamanRegister : responseSuccess(message: string)
deactivate UserController
    
HalamanRegister -> Pengguna : Tampilkan notifikasi berhasil
deactivate HalamanRegister
deactivate Pengguna

@enduml