@startuml SD-UC-A02_Login
title Sequence Diagram UC-A02: Masuk ke Akun Pengguna
skinparam style strictuml

actor Pengguna
boundary HalamanLogin
control UserController
entity User

activate Pengguna
Pengguna -> HalamanLogin : Mengakses halaman Login
activate HalamanLogin

HalamanLogin -> Pengguna : Tampilkan formulir login

Pengguna -> HalamanLogin : Input(email, password)

Pengguna -> HalamanLogin : Klik "Masuk"

HalamanLogin -> UserController : login(request: LoginRequest)
activate UserController

UserController -> User : validate(request.data)
activate User

UserController -> User : findByCredentials(email)


UserController -> User : verifyPassword(password, UserData.hash)

UserController -> User : createToken(UserData.id)

User --> UserController : UserData: User

deactivate User

UserController --> HalamanLogin : AuthResponse (token, user)
deactivate UserController

HalamanLogin -> Pengguna : Redirect ke '/dashboard'
deactivate HalamanLogin
deactivate Pengguna

@enduml