@startuml SD-UC-B02_MencariProduk
title Sequence Diagram UC-B02: Mencari Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog
control ProdukController
entity Produk

activate Pembeli
Pembeli -> HalamanKatalog : Input(keyword: string)
activate HalamanKatalog

Pembeli -> HalamanKatalog : Klik "Cari"

HalamanKatalog -> ProdukController : GET /produk?keyword={keyword}
activate ProdukController

ProdukController -> Produk : searchByKeyword(keyword: string)
activate Produk
Produk --> ProdukController : ProductList: List<Produk>
deactivate Produk

ProdukController --> HalamanKatalog : response(ProductList)
deactivate ProdukController

HalamanKatalog -> Pembeli : Tampilkan hasil pencarian
deactivate HalamanKatalog
deactivate Pembeli

@enduml