@startuml SD-UC-B04_MelihatDetailProduk
title Sequence Diagram UC-B04: Melihat Detail Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog
boundary HalamanDetailProduk
control ProdukController
entity Produk

activate Pembeli
Pembeli -> HalamanKatalog : Mengakses halaman katalog
activate HalamanKatalog

Pembeli -> HalamanKatalog : Klik produk(ID_Produk: integer)

HalamanKatalog -> ProdukController : GET /produk/{ID_Produk}
deactivate HalamanKatalog
activate ProdukController

ProdukController -> Produk : findById(ID_Produk: integer)
activate Produk
Produk --> ProdukController : ProductData: Produk
deactivate Produk

ProdukController --> HalamanDetailProduk : response(ProductData)
deactivate ProdukController
activate HalamanDetailProduk

HalamanDetailProduk -> Pembeli : Menampilkan seluruh informasi produk lengkap
deactivate HalamanDetailProduk
deactivate Pembeli

@enduml