@startuml SD-UC-B01_MelihatKatalog
title Sequence Diagram UC-B01: Melihat Seluruh Katalog Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog
control ProdukController
entity Produk

activate Pembeli
Pembeli -> HalamanKatalog : Akses '/dashboard/produk'
activate HalamanKatalog

HalamanKatalog -> ProdukController : GET /produk
activate ProdukController

ProdukController -> Produk : findByStatus(status: 'Aktif')
activate Produk
Produk --> ProdukController : ProductList: List<Produk>
deactivate Produk

ProdukController --> HalamanKatalog : response(ProductList)
deactivate ProdukController

HalamanKatalog -> Pembeli : Tampilkan seluruh katalog produk
deactivate HalamanKatalog
deactivate Pembeli

@enduml