@startuml SD-UC-B02_MencariProduk
'MASIH BLM FIX, ASLINYA TIDAK LEWAT BE, HANYA DI FE SAJA
title Sequence Diagram UC-B02: Mencari Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog

activate Pembeli

Pembeli -> HalamanKatalog : Input keyword pencarian & Enter
activate HalamanKatalog

HalamanKatalog -> HalamanKatalog : items = items.filter(query: String)

HalamanKatalog -> Pembeli : Tampilkan hasil pencarian
deactivate HalamanKatalog
deactivate Pembeli
@enduml