@startuml SD-UC-B01_MelihatKatalog
title Sequence Diagram UC-B01: Melihat Seluruh Katalog Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog
control LihatProdukController
entity Produk

activate Pembeli
Pembeli -> HalamanKatalog : Mengakses halaman '/produk'
activate HalamanKatalog

HalamanKatalog -> LihatProdukController : ambilSemuaProduk($request: Request)
activate LihatProdukController

LihatProdukController -> Produk : Produk::where('status_produk', 'Aktif')
activate Produk

Produk --> LihatProdukController : return(produk: Array)
deactivate Produk

LihatProdukController --> HalamanKatalog : response($data: Array)
deactivate LihatProdukController
    
HalamanKatalog -> Pembeli : Tampilkan daftar produk
deactivate HalamanKatalog
deactivate Pembeli
@enduml