@startuml SD-UC-B04_MelihatDetailProduk
title Sequence Diagram UC-B04: Melihat Detail Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog
boundary HalamanDetailProduk
control ProdukController
database produk as "produk\n(Database)"

' box "Sistem Katalog & Detail"
'     participant HalamanKatalog
'     participant HalamanDetailProduk
'     participant ProdukController
' end box

activate Pembeli
Pembeli -> HalamanKatalog : Mengakses halaman katalog (Langkah 1)
activate HalamanKatalog

Pembeli -> HalamanKatalog : Memilih salah satu produk (Langkah 2)

Pembeli -> HalamanKatalog : Menekan tombol Detail (Langkah 3)
HalamanKatalog -> ProdukController : ambilDetailProduk(ID_Produk)
deactivate HalamanKatalog
activate ProdukController

ProdukController -> produk : Query seluruh data detail produk (Langkah 4)
activate produk
return Data Produk Lengkap / Null (Langkah 4.a)

ProdukController -> HalamanDetailProduk : Tampilkan halaman detail(Data Produk) (Langkah 5)
deactivate ProdukController
activate HalamanDetailProduk

HalamanDetailProduk -> Pembeli : Menampilkan seluruh informasi produk lengkap (Langkah 6)
deactivate HalamanDetailProduk

' alt Jika Produk Ditemukan & Status='Aktif' (Main Flow)

' else Jika Produk Tidak Ditemukan / Status='Arsip' (Alternative Flow 4.a)
'     note over ProdukController
'         Menghentikan proses pengambilan data
'     end note
'     ProdukController -> HalamanKatalog : Tampilkan notifikasi("Maaf, Produk Saat Ini Tidak Tersedia") (Langkah 4.b)
'     deactivate ProdukController
'     activate HalamanKatalog
    
'     HalamanKatalog -> Pembeli : Menerima notifikasi
'     deactivate HalamanKatalog
' end alt
deactivate produk

@enduml