@startuml SD-UC-B04_MelihatDetailProduk
title Sequence Diagram UC-B04: Melihat Detail Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog
boundary HalamanDetailProduk
control LihatProdukController
entity Produk
database produks

activate Pembeli
Pembeli -> HalamanKatalog : Klik Card Produk

activate HalamanKatalog
HalamanKatalog -> HalamanDetailProduk : navigateTo('/produk/{ID_Produk}')
deactivate HalamanKatalog
activate HalamanDetailProduk

HalamanDetailProduk -> LihatProdukController : ambilDetailProduk($id: integer)
activate LihatProdukController

LihatProdukController -> Produk : Produk::where(id, status_aktif)->first()
activate Produk

Produk -> produks : SELECT * FROM produks WHERE ...
activate produks

produks --> Produk : return(produk: Produk)
deactivate produks

Produk --> LihatProdukController : return(produk: Produk)
deactivate Produk

LihatProdukController --> HalamanDetailProduk : response($data: Array)
deactivate LihatProdukController

HalamanDetailProduk -> Pembeli : Tampilkan detail produk tersebut
deactivate HalamanDetailProduk
deactivate Pembeli

@enduml