@startuml SD-UC-B02_MencariProduk
'MASIH BLM FIX, ASLINYA TIDAK LEWAT BE, HANYA DI FE SAJA
title Sequence Diagram UC-B02: Mencari Produk
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog
control LihatProdukController
entity Produk
database produks

activate Pembeli
Pembeli -> HalamanKatalog : Input keyword pencarian & Enter
activate HalamanKatalog

HalamanKatalog -> LihatProdukController : cariProduk($request: Request)
activate LihatProdukController

LihatProdukController -> Produk : Produk::query()->where('status_produk', 'Aktif')
activate Produk

LihatProdukController -> Produk : $query->where(...) // Filter by Name/Desc/Category
Produk -> produks : SELECT * FROM produks WHERE ... LIMIT 10 OFFSET 0
activate produks
produks --> Produk : return(Result: Paginator)
deactivate produks

Produk --> LihatProdukController : return(produks: LengthAwarePaginator)
deactivate Produk

LihatProdukController --> HalamanKatalog : response()->json($produks, 200)
deactivate LihatProdukController

HalamanKatalog -> Pembeli : Tampilkan hasil pencarian
deactivate HalamanKatalog
deactivate Pembeli
@enduml