@startuml SD-UC-B03_MemfilterProduk
'MASIH BLM FIX, ASLINYA TIDAK LEWAT BE, HANYA DI FE SAJA
title Sequence Diagram UC-B03: Memfilter Produk Berdasarkan Kriteria
skinparam style strictuml

actor Pembeli
boundary HalamanKatalog

activate Pembeli
Pembeli -> HalamanKatalog : Akses halaman katalog
activate HalamanKatalog

HalamanKatalog -> HalamanKatalog : items = items.filter(category: String)

HalamanKatalog -> Pembeli : Tampilkan produk yang tersaring
deactivate HalamanKatalog
deactivate Pembeli

@enduml