@startuml SD-UC-C03_HapusKeranjang
title Sequence Diagram UC-C03: Menghapus Produk dari Keranjang Belanja
skinparam style strictuml

actor Pembeli
boundary HalamanKeranjang

activate Pembeli

Pembeli -> HalamanKeranjang : Klik logo hapus
activate HalamanKeranjang

HalamanKeranjang -> HalamanKeranjang : removeItem(id_detail: String)
HalamanKeranjang -> Pembeli : Tampilkan keranjang terbaru
deactivate HalamanKeranjang
deactivate Pembeli

@enduml