@startuml SD-UC-C04_UbahKuantitas
title Sequence Diagram UC-C04: Mengubah Kuantitas Produk di Keranjang Belanja
skinparam style strictuml

actor Pembeli
boundary HalamanKeranjang

activate Pembeli

Pembeli -> HalamanKeranjang : Klik tombol + atau - pada kuantitas
activate HalamanKeranjang

HalamanKeranjang -> HalamanKeranjang : changeQty(item)

HalamanKeranjang -> Pembeli : Tampilkan perubahan kuantitas
deactivate HalamanKeranjang
deactivate Pembeli

@enduml