@startuml SD-UC-C03_HapusKeranjang
title Sequence Diagram UC-C03: Menghapus Produk dari Keranjang Belanja
skinparam style strictuml

actor Pembeli
boundary HalamanKeranjang
control KeranjangController
database detail_pesanan as "detail_pesanan\n(Keranjang)"

' box "Sistem Transaksi"
'     participant HalamanKeranjang
'     participant KeranjangController
' end box

activate Pembeli
Pembeli -> HalamanKeranjang : Mengakses halaman Keranjang Belanja (Langkah 1)
activate HalamanKeranjang
HalamanKeranjang -> Pembeli : Tampilkan daftar produk di keranjang (Langkah 1 & 2)

Pembeli -> HalamanKeranjang : Menekan tombol "hapus" (Langkah 3)

HalamanKeranjang -> KeranjangController : hapusItemKeranjang(ID_ItemKeranjang)
activate KeranjangController

KeranjangController -> detail_pesanan : Validasi perintah hapus (Langkah 4)

KeranjangController -> detail_pesanan : Hapus item dari database
activate detail_pesanan
return Status Operasi (Berhasil/Gagal)

KeranjangController -> HalamanKeranjang : Muat ulang keranjang dan notifikasi("Produk berhasil dihapus") (Langkah 6)
deactivate KeranjangController

HalamanKeranjang -> Pembeli : Melihat daftar keranjang terbaru (Langkah 7)

' alt Jika Proses Penghapusan Gagal (Alternative Flow 4.a)
'     note over KeranjangController
'         Kegagalan koneksi/Item tidak ditemukan
'     end note
'     KeranjangController -> HalamanKeranjang : Tampilkan notifikasi("Gagal: Produk tidak dapat dihapus...") (Langkah 4.b)
'     deactivate KeranjangController
    
'     HalamanKeranjang -> Pembeli : Menerima notifikasi gagal
    
'     note over Pembeli, HalamanKeranjang
'         Mencoba kembali (Langkah 4.c)
'         Kembali ke Langkah 3 (Langkah 4.d)
'     end note
' else Jika Proses Penghapusan Berhasil (Main Flow)

' end alt

deactivate HalamanKeranjang
deactivate detail_pesanan

@enduml