@startuml SD-UC-C02_MelihatKeranjang
title Sequence Diagram UC-C02: Melihat Daftar Keranjang Belanja
skinparam style strictuml

actor Pembeli
boundary HalamanDashboard
boundary HalamanKeranjang
control CartController
entity DetailPesanan

activate Pembeli
Pembeli -> HalamanDashboard : Mengakses dashboard
activate HalamanDashboard

Pembeli -> HalamanDashboard : Klik "Keranjang"
deactivate HalamanDashboard

HalamanKeranjang -> CartController : GET /cart
activate CartController

CartController -> DetailPesanan : findActiveCartByUserId(auth_id: integer)
activate DetailPesanan

CartController -> DetailPesanan : calculateSubtotal(CartItems)

DetailPesanan --> CartController : CartItems: List<Item>
deactivate DetailPesanan


CartController --> HalamanKeranjang : response(CartItems, Subtotal)
deactivate CartController
activate HalamanKeranjang

HalamanKeranjang -> Pembeli : Tampilkan daftar keranjang produk
deactivate HalamanKeranjang
deactivate Pembeli

@enduml