@startuml SD-UC-C02_MelihatKeranjang
title Sequence Diagram UC-C02: Melihat Daftar Keranjang Belanja
skinparam style strictuml

actor Pembeli
boundary HalamanDashboard
boundary HalamanKeranjang

activate Pembeli

Pembeli -> HalamanDashboard : Klik logo keranjang
activate HalamanDashboard

HalamanDashboard -> HalamanKeranjang : navigateTo('/keranjang')
activate HalamanKeranjang
deactivate HalamanDashboard

HalamanKeranjang -> HalamanKeranjang : cartItems.value = cart.value.items

HalamanKeranjang -> Pembeli : Menampilkan daftar keranjang
deactivate HalamanKeranjang
deactivate Pembeli

@enduml