@startuml SD-UC-C01_TambahKeranjang
title Sequence Diagram UC-C01: Menambahkan Produk ke Keranjang Belanja
skinparam style strictuml

actor Pembeli
boundary HalamanDetailProduk
boundary HalamanKeranjang

activate Pembeli

Pembeli -> HalamanDetailProduk : Klik "Tambah ke Keranjang"
activate HalamanDetailProduk

HalamanDetailProduk -> HalamanDetailProduk : addToCart(produkID: integer, jumlah: integer)
HalamanDetailProduk -> HalamanKeranjang : navigateTo('/keranjang')
deactivate HalamanDetailProduk
activate HalamanKeranjang

HalamanKeranjang -> Pembeli : Tampilkan halaman keranjang
deactivate Pembeli

@enduml