@startuml SD-UC-D01_MelakukanProsesPemesanan
title Sequence Diagram UC-D01: Melakukan Proses Pemesanan
skinparam style strictuml

actor Pembeli
boundary HalamanCheckout
boundary HalamanDetailTransaksi
control TambahPesananController
entity Pesanan
entity Produk
entity DetailPesanan
entity Pembayaran

activate Pembeli
Pembeli -> HalamanCheckout : Klik "Beli Sekarang"
activate HalamanCheckout

HalamanCheckout -> TambahPesananController : buatPesanan($request: Request)
activate TambahPesananController

TambahPesananController -> TambahPesananController : validate($request: Request)

TambahPesananController -> Pesanan : Pesanan::create($data: Array)
activate Pesanan

Pesanan --> TambahPesananController : return(pesanan: Pesanan)
deactivate Pesanan

loop each $request->items as $item
    TambahPesananController -> Produk : Produk::find($item.id: Integer)
    activate Produk

    Produk --> TambahPesananController : return(produk: Produk)
    deactivate Produk

    TambahPesananController -> DetailPesanan : DetailPesanan::create($pesanan.id: Integer, $item: Array)
    activate DetailPesanan

    DetailPesanan --> TambahPesananController : return(detail_pesanan: DetailPesanan)
    deactivate DetailPesanan
end

TambahPesananController -> Pembayaran : Pembayaran::create($data: Array)
activate Pembayaran

Pembayaran --> TambahPesananController : return(pembayaran: Pembayaran)
deactivate Pembayaran

TambahPesananController --> HalamanCheckout : response($data: Array)
deactivate TambahPesananController

HalamanCheckout -> HalamanDetailTransaksi : navigateTo('/transaksi/{id_pesanan})
deactivate HalamanCheckout
activate HalamanDetailTransaksi

HalamanDetailTransaksi -> Pembeli : Tampilkan halaman detail transaksi
deactivate HalamanDetailTransaksi
deactivate Pembeli

@enduml