@startuml SD-UC-D02_MelakukanKonfirmasiPembayaran
title Sequence Diagram UC-D02: Melakukan Konfirmasi Pembayaran
skinparam style strictuml

actor Pembeli
boundary HalamanPembayaran
boundary HalamanTransaksi
control KonfirmasiPembayaranController
entity Pembayaran
entity Pesanan

activate Pembeli
Pembeli -> HalamanPembayaran : Klik "Konfirmasi Pembayaran"
activate HalamanPembayaran

HalamanPembayaran -> KonfirmasiPembayaranController : perbaruiStatusPembayaran($request: Request)
activate KonfirmasiPembayaranController

KonfirmasiPembayaranController -> Pembayaran : where('id_pesanan', $request->id_pesanan)
activate Pembayaran

Pembayaran --> KonfirmasiPembayaranController : return(pembayaran: Pembayaran)
deactivate Pembayaran

KonfirmasiPembayaranController -> Pesanan : update($status: String)
activate Pesanan

Pesanan --> KonfirmasiPembayaranController : return(true: Boolean)
deactivate Pesanan

KonfirmasiPembayaranController --> HalamanPembayaran : response($data: Array)
deactivate KonfirmasiPembayaranController

HalamanPembayaran -> HalamanTransaksi : navigateTo('/transaksi')
deactivate HalamanPembayaran
activate HalamanTransaksi

HalamanTransaksi -> Pembeli : Tampilkan notifikasi sukses
deactivate HalamanTransaksi
deactivate Pembeli

@enduml