@startuml SD-UC-E02_MelihatDetailPesanan
title Sequence Diagram UC-E02: Melihat Detail Pesanan
skinparam style strictuml

actor Pembeli
boundary HalamanTransaksi as "Halaman Transaksi Saya"
boundary HalamanDetailPesanan
control PesananController
entity Pesanan

activate Pembeli
Pembeli -> HalamanTransaksi : Mengakses riwayat pesanan
activate HalamanTransaksi

Pembeli -> HalamanTransaksi : Mengklik detail pesanan (ID_Pesanan: integer)
HalamanTransaksi -> PesananController : GET /pesanan/{ID_Pesanan}
deactivate HalamanTransaksi
activate PesananController

PesananController -> Pesanan : findDetailById(ID_Pesanan)
activate Pesanan
Pesanan --> PesananController : Data Pesanan Lengkap: Pesanan
deactivate Pesanan

PesananController --> HalamanDetailPesanan : response(Data Pesanan Lengkap)
deactivate PesananController
activate HalamanDetailPesanan

HalamanDetailPesanan -> Pembeli : Meninjau detail pesanan
deactivate HalamanDetailPesanan
deactivate Pembeli

@enduml