@startuml SD-UC-E01_MelihatDaftarPesanan
title Sequence Diagram UC-E01: Melihat Daftar Seluruh Pesanan
skinparam style strictuml

actor Pembeli
boundary HalamanTransaksi as "Halaman Transaksi Saya"
control PesananController
entity Pesanan

activate Pembeli
Pembeli -> HalamanTransaksi : Mengakses halaman "/dashboard/transaksi"
activate HalamanTransaksi

HalamanTransaksi -> PesananController : GET /pesanan
activate PesananController

PesananController -> Pesanan : findByUserId(auth_id)
activate Pesanan
Pesanan --> PesananController : List Ringkasan Pesanan: List<Pesanan>
deactivate Pesanan

PesananController --> HalamanTransaksi : response(List Pesanan)
deactivate PesananController

HalamanTransaksi -> Pembeli : Tampilkan daftar ringkasan pesanan
deactivate HalamanTransaksi
deactivate Pembeli

@enduml