@startuml SD-UC-E01_MelihatDaftarPesanan
title Sequence Diagram UC-E01: Melihat Daftar Seluruh Pesanan
skinparam style strictuml

actor Pembeli
boundary HalamanTransaksi
control LihatPesananController
entity Pesanan
database pesanans

activate Pembeli

Pembeli -> HalamanTransaksi : Mengakses halaman "/dashboard/transaksi"
activate HalamanTransaksi

HalamanTransaksi -> LihatPesananController : ambilDaftarPesanan($request: Request)
activate LihatPesananController

LihatPesananController -> Pesanan : Pesanan::where('user_id', auth_id)
activate Pesanan

Pesanan -> pesanans : SELECT * FROM pesanans WHERE ...
activate pesanans

pesanans --> Pesanan : return(pesanan: Array)
deactivate pesanans

Pesanan --> LihatPesananController : return(pesanan: Array)
deactivate Pesanan

LihatPesananController --> HalamanTransaksi : response($data: Array)
deactivate LihatPesananController

HalamanTransaksi -> Pembeli : Tampilkan daftar ringkasan pesanan
deactivate HalamanTransaksi
deactivate Pembeli

@enduml