@startuml SD-UC-E02_MelihatDetailPesanan
title Sequence Diagram UC-E02: Melihat Detail Pesanan
skinparam style strictuml

actor Pembeli
boundary HalamanTransaksi
boundary HalamanDetailTransaksi
control LihatPesananController
entity Pesanan

activate Pembeli

Pembeli -> HalamanTransaksi : Klik Card Transaksi
activate HalamanTransaksi

HalamanTransaksi -> HalamanDetailTransaksi : navigateTo('/transaksi/{id_pesanan}')
deactivate HalamanTransaksi
activate HalamanDetailTransaksi

HalamanDetailTransaksi -> LihatPesananController : ambilDetailPesanan($id: int)
activate LihatPesananController

LihatPesananController -> Pesanan : Pesanan::where(id_pembeli, id_pesanan, first())
activate Pesanan

Pesanan --> LihatPesananController : return(pesanan: Pesanan)
deactivate Pesanan

LihatPesananController --> HalamanDetailTransaksi : response($data: Array)
deactivate LihatPesananController

HalamanDetailTransaksi -> Pembeli : Tampilkan halaman detail pesanan
deactivate HalamanDetailTransaksi
deactivate Pembeli

@enduml