@startuml SD-UC-E02_MelihatDetailPesanan
title Sequence Diagram UC-E02: Melihat Detail Pesanan
skinparam style strictuml

actor Pembeli
boundary HalamanTransaksi
boundary HalamanDetailTransaksi
control LihatPesananController
entity Pesanan
database pesanans

activate Pembeli

Pembeli -> HalamanTransaksi : Klik Card Transaksi
activate HalamanTransaksi

HalamanTransaksi -> HalamanDetailTransaksi : navigateTo('/transaksi/{id_pesanan}')
deactivate HalamanTransaksi
activate HalamanDetailTransaksi

HalamanDetailTransaksi -> PesananController : ambilDetailPesanan($id: int)
activate PesananController

PesananController -> Pesanan : Pesanan::where(id_pembeli, id_pesanan, first())
activate Pesanan

Pesanan -> pesanans : SELECT * FROM pesanans WHERE ...
activate pesanans

pesanans --> Pesanan : return(pesanan: Pesanan)
deactivate pesanans

Pesanan --> PesananController : return(pesanan: Pesanan)
deactivate Pesanan

PesananController --> HalamanDetailTransaksi : response($data: Array)
deactivate PesananController

HalamanDetailTransaksi -> Pembeli : Tampilkan halaman detail pesanan
deactivate HalamanDetailTransaksi
deactivate Pembeli

@enduml