@startuml SD-UC-F01_MengirimPengaduan
title Sequence Diagram UC-F01: Mengirim Laporan Pengaduan Produk
skinparam style strictuml

actor Pembeli
boundary HalamanAduan
boundary HalamanTransaksi
control TambahKomplainController
entity Komplain

activate Pembeli
Pembeli -> HalamanAduan : Klik "Kirim Aduan"
activate HalamanAduan

HalamanAduan -> TambahKomplainController : kirimAduan($request: Request)
activate TambahKomplainController

TambahKomplainController -> TambahKomplainController : validate($request)

TambahKomplainController -> Komplain : create($data: Array)
activate Komplain

Komplain --> TambahKomplainController : return(komplain: Komplain)
deactivate Komplain

TambahKomplainController --> HalamanAduan : response(data: Array)
deactivate TambahKomplainController

HalamanAduan --> Pembeli : Tampilkan notifikasi sukses
HalamanAduan -> HalamanTransaksi : navigateTio('/transaksi')
deactivate HalamanAduan
activate HalamanTransaksi

HalamanTransaksi -> Pembeli : Tampilkan halaman transaksi
deactivate HalamanTransaksi
deactivate Pembeli

@enduml