@startuml SD-UC-F01_MengirimPengaduan
title Sequence Diagram UC-F01: Mengirim Laporan Pengaduan Produk
skinparam style strictuml

actor Pembeli
boundary HalamanAduan
boundary HalamanTransaksi
control TambahKomplainController
entity Komplain
database komplains

activate Pembeli
Pembeli -> HalamanAduan : Klik "Kirim Aduan"
activate HalamanAduan

HalamanAduan -> KomplainController : kirimAduan($request: Request)
activate KomplainController

KomplainController -> KomplainController : validate($request)

KomplainController -> Komplain : create($data: Array)
activate Komplain

Komplain -> komplains : INSERT INTO komplains ...
activate komplains

komplains --> Komplain : return(komplain: Komplain)
deactivate komplains

Komplain --> KomplainController : return(komplain: Komplain)
deactivate Komplain

KomplainController --> HalamanAduan : response(data: Array)
deactivate KomplainController

HalamanAduan --> Pembeli : Tampilkan notifikasi sukses
HalamanAduan -> HalamanTransaksi : navigateTio('/transaksi')
deactivate HalamanAduan
activate HalamanTransaksi

HalamanTransaksi -> Pembeli : Tampilkan halaman transaksi
deactivate HalamanTransaksi
deactivate Pembeli

@enduml