@startuml SD-UC-G01_MembacaBerita
title Sequence Diagram UC-G01: Menelusuri dan Membaca Informasi Berita
skinparam style strictuml

actor Pembeli
boundary HalamanDaftarBerita
boundary HalamanDetailBerita
control BeritaController
entity Berita

activate Pembeli
Pembeli -> HalamanDaftarBerita : Mengakses halaman berita
activate HalamanDaftarBerita

HalamanDaftarBerita -> BeritaController : GET /berita
activate BeritaController

BeritaController -> Berita : findPublished()
activate Berita
Berita --> BeritaController : List Ringkasan Berita: List<Berita>
deactivate Berita

BeritaController --> HalamanDaftarBerita : response(List Ringkasan Berita)
deactivate BeritaController

HalamanDaftarBerita -> Pembeli : Tampilkan daftar ringkasan berita

Pembeli -> HalamanDaftarBerita : Memilih berita (ID_Berita: integer)
HalamanDaftarBerita -> BeritaController : GET /berita/{ID_Berita}
deactivate HalamanDaftarBerita
activate BeritaController

BeritaController -> Berita : findById(ID_Berita)
activate Berita
Berita --> BeritaController : Data Detail Berita: Berita
deactivate Berita

BeritaController --> HalamanDetailBerita : response(Data Detail Berita)
deactivate BeritaController
activate HalamanDetailBerita

HalamanDetailBerita -> Pembeli : Tampilkan seluruh konten berita
deactivate HalamanDetailBerita
deactivate Pembeli

@enduml