@startuml SD-UC-H01_MelihatDaftarProdukAdmin
title Sequence Diagram UC-H01: Melihat Daftar Produk (Admin)
skinparam style strictuml

actor Admin
boundary HalamanKelolaProduk
control LihatProdukController
entity Produk

activate Admin

Admin -> HalamanKelolaProduk : Mengakses halaman '/admin/produk'
activate HalamanKelolaProduk

HalamanKelolaProduk -> LihatProdukController : ambilSemuaProduk()
activate LihatProdukController

LihatProdukController -> Produk : Produk::all()
activate Produk

Produk --> LihatProdukController : return(produk: Array)
deactivate Produk

LihatProdukController --> HalamanKelolaProduk : response($data: Array)
deactivate LihatProdukController
    
HalamanKelolaProduk -> Admin : Tampilkan daftar produk
deactivate HalamanKelolaProduk
deactivate Admin

@enduml