@startuml SD-UC-H05_PerbaruiStok
title Sequence Diagram UC-H05: Memperbarui Stok Produk
skinparam style strictuml

actor Admin
boundary HalamanUbahProduk
boundary HalamanKelolaProduk
control UbahProdukController
entity Produk

activate Admin

Admin -> HalamanUbahProduk : Klik "Perbarui Produk"
activate HalamanUbahProduk

HalamanUbahProduk -> UbahProdukController : ubahProduk(request: Request, id: int)
activate UbahProdukController

UbahProdukController -> Produk : Produk::where(id_produk).update(stok: integer)
activate Produk

Produk --> UbahProdukController : return(produk: Produk)
deactivate Produk

UbahProdukController --> HalamanUbahProduk : response(produk: Produk)
deactivate UbahProdukController

HalamanUbahProduk -> Admin : Tampilkan notifikasi berhasil
HalamanUbahProduk -> HalamanKelolaProduk : navigateTo('/admin/produk')
deactivate HalamanUbahProduk
activate HalamanKelolaProduk

HalamanKelolaProduk -> Admin : Tampilkan daftar produk terbaru
deactivate HalamanKelolaProduk
deactivate Admin

@enduml