@startuml SD-UC-H04_MengarsipkanProduk
title Sequence Diagram UC-H04: Mengarsipkan Produk
skinparam style strictuml

actor Admin
boundary HalamanKelolaProduk
control ProdukController
entity produk
' box "Sistem Manajemen Produk"
'     participant HalamanKelolaProduk
'     participant ProdukController
' end box

activate Admin
Admin -> HalamanKelolaProduk : Mengakses halaman kelola produk (Langkah 1)
activate HalamanKelolaProduk

HalamanKelolaProduk -> Admin : Tampilkan daftar seluruh katalog produk (Langkah 1 & 2)

Admin -> HalamanKelolaProduk : Memilih produk & menekan tombol "Arsipkan" (Langkah 3)
' HalamanKelolaProduk -> HalamanKelolaProduk : Tampilkan kotak dialog konfirmasi (Langkah 3)

' Admin -> HalamanKelolaProduk : Memilih "Ya, Arsipkan" / "Batal" (Langkah 4 / 4.a)

HalamanKelolaProduk -> ProdukController : arsipProduk(ID_Produk)
activate ProdukController

ProdukController -> produk : Memproses pembaruan status menjadi 'Arsip' (Langkah 5)
activate produk
return Status Operasi
deactivate produk

ProdukController -> HalamanKelolaProduk : Tampilkan notifikasi("Produk berhasil diarsipkan") (Langkah 6)

ProdukController -> HalamanKelolaProduk : Perbarui daftar kelola produk (Langkah 7)
deactivate ProdukController

HalamanKelolaProduk -> Admin : Menerima notifikasi sukses dan daftar terbaru

' alt Jika Admin Memilih "Ya, Arsipkan" (Main Flow)

' else Jika Admin Memilih "Batal" (Alternative Flow 4.a)
'     HalamanKelolaProduk -> ProdukController : batalkanPengarsipan(ID_Produk)
'     activate ProdukController
    
'     ProdukController -> HalamanKelolaProduk : Berikan notifikasi("Pengarsipan dibatalkan.") (Langkah 5.a)
'     deactivate ProdukController
    
'     HalamanKelolaProduk -> Admin : Menerima notifikasi pembatalan (Langkah 5.a)
' end alt

deactivate HalamanKelolaProduk

@enduml