@startuml SD-UC-H01_MelihatDaftarProdukAdmin
title Sequence Diagram UC-H01: Melihat Daftar Produk (Admin)
skinparam style strictuml

actor Admin
boundary HalamanKelolaProduk
control ProdukController
control PesananController
entity produk

' box "Sistem Manajemen Produk"
'     participant HalamanKelolaProduk
'     participant ProdukController
' end box

activate Admin
Admin -> HalamanKelolaProduk : Mengakses halaman "Kelola Produk" (Langkah 1)
activate HalamanKelolaProduk

HalamanKelolaProduk -> ProdukController : ambilSemuaProdukAdmin()
activate ProdukController

ProdukController -> produk : Mengambil daftar seluruh produk (Aktif & Arsip) (Langkah 2)
activate produk
return List Produk Lengkap / List Kosong (Langkah 2.a)
deactivate produk

PesananController -> HalamanKelolaProduk : Tampilkan daftar ringkasan produk (Langkah 3)
deactivate ProdukController

HalamanKelolaProduk -> Admin : Melihat daftar produk dan opsi aksi (Langkah 4)

' alt Jika Produk Ditemukan (Main Flow)

' else Jika Daftar Kosong (Alternative Flow 2.a)
'     note over ProdukController
'         List Produk Kosong
'     end note
'     ProdukController -> HalamanKelolaProduk : Tampilkan notifikasi("Belum ada produk yang ditambahkan.") (Langkah 3.a)
'     deactivate ProdukController
    
'     HalamanKelolaProduk -> Admin : Menerima notifikasi daftar kosong (Langkah 4)
' end alt
deactivate HalamanKelolaProduk

@enduml