@startuml SD-UC-H03_HapusProduk
title Sequence Diagram UC-H03: Menghapus Produk
skinparam style strictuml

actor Admin
boundary HalamanKelolaProduk
control HapusProdukController
entity Produk
database produks

activate Admin

Admin -> HalamanKelolaProduk : Klik "Hapus" 
activate HalamanKelolaProduk

HalamanKelolaProduk -> HapusProdukController : hapusProduk(id_produk: integer)
activate HapusProdukController

HapusProdukController -> Produk : Produk::deleteById(id_produk: integer)
activate Produk

Produk -> produks : DELETE FROM produks WHERE id_produk = ...
activate produks

produks --> Produk : return(true: boolean)
deactivate produks

Produk --> HapusProdukController : return(true: boolean)
deactivate Produk

HapusProdukController --> HalamanKelolaProduk : response(data: Array)
deactivate HapusProdukController

HalamanKelolaProduk -> Admin : Tampilkan notifikasi & list baru
deactivate HalamanKelolaProduk
deactivate Admin

@enduml