@startuml SD-UC-H03_HapusProduk
title Sequence Diagram UC-H03: Menghapus Produk
skinparam style strictuml

actor Admin
boundary HalamanKelolaProduk
control ProdukController
entity Produk

activate Admin
Admin -> HalamanKelolaProduk : Mengakses halaman kelola produk
activate HalamanKelolaProduk

HalamanKelolaProduk -> Admin : Tampilkan daftar seluruh produk

Admin -> HalamanKelolaProduk : Klik "Hapus" (ID_Produk: integer)

HalamanKelolaProduk -> ProdukController : DELETE /admin/produk/{ID_Produk}
activate ProdukController

ProdukController -> Produk : deleteById(ID_Produk: integer)
activate Produk
Produk --> ProdukController : deleteStatus: boolean
deactivate Produk

ProdukController --> HalamanKelolaProduk : responseSuccess(message: string)
deactivate ProdukController

HalamanKelolaProduk -> Admin : Tampilkan notifikasi sukses dan daftar terbaru
deactivate HalamanKelolaProduk
deactivate Admin

@enduml