@startuml SD-UC-H04_MengarsipkanProduk
title Sequence Diagram UC-H04: Mengarsipkan Produk
skinparam style strictuml

actor Admin
boundary HalamanKelolaProduk
control UbahProdukController
entity Produk
database produks

activate Admin

Admin -> HalamanKelolaProduk : Klik "Arsipkan"
activate HalamanKelolaProduk

HalamanKelolaProduk -> UbahProdukController : ubahProduk(request: Request, id: int)
activate UbahProdukController

UbahProdukController -> Produk : Produk::where(id_produk).update(status_produk: 'Arsip')
activate Produk

Produk -> produks : UPDATE produks SET status_produk = 'Arsip' WHERE id_produk = ...
activate produks

produks --> Produk : return(true: boolean)
deactivate produks

Produk --> UbahProdukController : return(true: boolean)
deactivate Produk

UbahProdukController --> HalamanKelolaProduk : response(data: Array)
deactivate UbahProdukController

HalamanKelolaProduk -> Admin : Tampilkan notifikasi & list baru
deactivate HalamanKelolaProduk
deactivate Admin

@enduml