@startuml SD-UC-IO2_UpdateStatusPesanan
title Sequence Diagram UC-I02: Memperbarui Status
skinparam style strictuml

actor Admin
boundary HalamanPesananAdmin
control UbahPesananController
entity Pesanan

activate Admin

Admin -> HalamanPesananAdmin : Klik "Konfirmasi" / "Kirim Pesanan" / "Selesaikan"
activate HalamanPesananAdmin

HalamanPesananAdmin -> UbahPesananController : updateStatus(request: Request, id: int)
activate UbahPesananController

UbahPesananController -> UbahPesananController : validate($request)
UbahPesananController -> Pesanan : Pesanan::where(id_pesanan).update(status_pesanan: string)
activate Pesanan

Pesanan --> UbahPesananController : return(pesanan: Pesanan)
deactivate Pesanan

UbahPesananController --> HalamanPesananAdmin : response(data: Array)
deactivate UbahPesananController

HalamanPesananAdmin -> Admin : Tampilkan perubahan status
deactivate HalamanPesananAdmin
deactivate Admin

@enduml