@startuml SD-UC-I01_MelihatDaftarPesananAdmin
title Sequence Diagram UC-I01: Melihat Daftar Pesanan yang Masuk (Admin)
skinparam style strictuml

actor Admin
boundary HalamanDaftarPesanan
control PesananController
entity Pesanan

activate Admin
Admin -> HalamanDaftarPesanan : Mengakses halaman "/admin/pesanan"
activate HalamanDaftarPesanan

HalamanDaftarPesanan -> PesananController : GET /admin/pesanan
activate PesananController

PesananController -> Pesanan : findAll()
activate Pesanan
Pesanan --> PesananController : List Pesanan Lengkap: List<Pesanan>
deactivate Pesanan

PesananController --> HalamanDaftarPesanan : response(List Pesanan)
deactivate PesananController

HalamanDaftarPesanan -> Admin : Melihat dan meninjau daftar pesanan
deactivate HalamanDaftarPesanan
deactivate Admin

@enduml