@startuml SD-UC-I01_MelihatDaftarPesananAdmin
title Sequence Diagram UC-I01: Melihat Daftar Pesanan (Admin)
skinparam style strictuml

actor Admin
boundary HalamanDaftarPesanan
control LihatSemuaPesananController
entity Pesanan

activate Admin

Admin -> HalamanDaftarPesanan : Mengakses halaman "/admin/pesanan"
activate HalamanDaftarPesanan

HalamanDaftarPesanan -> LihatSemuaPesananController : ambilSemuaPesanan()
activate LihatSemuaPesananController

LihatSemuaPesananController -> Pesanan : Pesanan::all()
activate Pesanan

Pesanan --> LihatSemuaPesananController : return(pesanan: Array)
deactivate Pesanan

LihatSemuaPesananController --> HalamanDaftarPesanan : response(pesanan: Array)
deactivate LihatSemuaPesananController

HalamanDaftarPesanan -> Admin : Tampilkan daftar pesanan
deactivate HalamanDaftarPesanan
deactivate Admin

@enduml