@startuml SD-UC-IO2_UpdateStatusPesanan
title Sequence Diagram UC-I02: Memperbarui Status Pesanan Pembeli
skinparam style strictuml

actor Admin
boundary HalamanPesananAdmin
control PesananController
entity Pesanan

activate Admin
Admin -> HalamanPesananAdmin : Mengakses halaman "/admin/pesanan"
activate HalamanPesananAdmin

HalamanPesananAdmin -> Admin : Tampilkan daftar pesanan

Admin -> HalamanPesananAdmin : Pilih dan Simpan Status Baru (status: string)

HalamanPesananAdmin -> PesananController : PATCH /admin/pesanan/{ID_Pesanan} (request: object)
activate PesananController

PesananController -> Pesanan : validate(request.data)
activate Pesanan

PesananController -> Pesanan : updateStatus(ID_Pesanan, request.status)
Pesanan --> PesananController : updateStatus: boolean
deactivate Pesanan

PesananController --> HalamanPesananAdmin : responseSuccess(message: string)
deactivate PesananController

HalamanPesananAdmin -> Admin : Tampilkan notifikasi sukses dan muat ulang daftar
deactivate HalamanPesananAdmin
deactivate Admin

@enduml