@startuml SD-UC-J01_MelihatKomplainProduk
title Sequence Diagram UC-J01: Melihat Komplain Produk (Admin)
skinparam style strictuml

actor Admin
boundary HalamanDaftarPengaduan
boundary HalamanDetailKomplain
control LihatKomplainController
entity Komplain
database komplains

activate Admin

Admin -> HalamanDaftarPengaduan : Mengakses halaman "/admin/aduan"
activate HalamanDaftarPengaduan

HalamanDaftarPengaduan -> LihatKomplainController : ambilDaftarKomplain($request: Request)
activate LihatKomplainController

LihatKomplainController -> Komplain : Komplain::all()
activate Komplain

Komplain -> komplains : SELECT * FROM komplains
activate komplains

komplains --> Komplain : return(komplains: Array)
deactivate komplains

Komplain --> LihatKomplainController : return(komplains: Array)
deactivate Komplain

LihatKomplainController --> HalamanDaftarPengaduan : response(komplains: Array)
deactivate LihatKomplainController

HalamanDaftarPengaduan -> Admin : Tampilkan daftar pengaduan
Admin -> HalamanDaftarPengaduan : Klik 'Lihat Detail' pada salah 1 pengaduan

HalamanDaftarPengaduan -> HalamanDetailKomplain : navigateTo('/admin/aduan/{id_komplain}')
deactivate HalamanDaftarPengaduan
activate HalamanDetailKomplain

HalamanDetailKomplain -> LihatKomplainController : ambilDetailKomplain($id: int)
activate LihatKomplainController

LihatKomplainController -> Komplain : Komplain::where(id_komplain, first())
activate Komplain

Komplain -> komplains : SELECT * FROM komplains WHERE ...
activate komplains

komplains --> Komplain : return(komplain: Komplain)
deactivate komplains

Komplain --> LihatKomplainController : return(komplain: Komplain)
deactivate Komplain

LihatKomplainController --> HalamanDetailKomplain : response(data: Array)
deactivate LihatKomplainController

HalamanDetailKomplain -> Admin : Tampilkan detail pengaduan
deactivate HalamanDetailKomplain
deactivate Admin

@enduml