@startuml SD-UC-J01_MelihatKomplainProduk
title Sequence Diagram UC-J01: Melihat Komplain Produk (Admin)
skinparam style strictuml

actor Admin
boundary HalamanPusatPengaduan
boundary HalamanDetailKomplain
control KomplainController
entity Komplain

activate Admin
Admin -> HalamanPusatPengaduan : Mengakses halaman "/admin/aduan"
activate HalamanPusatPengaduan

HalamanPusatPengaduan -> KomplainController : GET /admin/komplain
activate KomplainController

KomplainController -> Komplain : findAll()
activate Komplain
Komplain --> KomplainController : List Ringkasan Komplain: List<Komplain>
deactivate Komplain

KomplainController --> HalamanPusatPengaduan : response(List Ringkasan Komplain)
deactivate KomplainController

HalamanPusatPengaduan -> Admin : Tampilkan daftar ringkasan pengaduan

Admin -> HalamanPusatPengaduan : Klik laporan (ID_Komplain: integer)

HalamanPusatPengaduan -> KomplainController : GET /admin/komplain/{ID_Komplain}
activate KomplainController

KomplainController -> Komplain : findById(ID_Komplain: integer)
activate Komplain
Komplain --> KomplainController : Data Detail Komplain: Komplain
deactivate Komplain

KomplainController --> HalamanDetailKomplain : response(Data Detail Komplain)
deactivate KomplainController
activate HalamanDetailKomplain

HalamanDetailKomplain -> Admin : Melihat dan meninjau detail laporan
deactivate HalamanDetailKomplain
deactivate Admin

@enduml