@startuml SD-UC-J01_MelihatKomplainProduk
title Sequence Diagram UC-J01: Melihat Komplain Produk (Admin)
skinparam style strictuml

actor Admin
boundary HalamanPusatPengaduan
boundary HalamanDetailKomplain
control KomplainController
entity komplain

' box "Sistem Penanganan Komplain"
'     participant HalamanPusatPengaduan
'     participant HalamanDetailKomplain
'     participant KomplainController
' end box

activate Admin
Admin -> HalamanPusatPengaduan : Mengakses halaman pusat pengaduan (Langkah 1)
activate HalamanPusatPengaduan

HalamanPusatPengaduan -> KomplainController : ambilDaftarKomplainAktif()
activate KomplainController

KomplainController -> komplain : Mengambil daftar pengaduan (Status 'Baru' atau 'Dalam Proses') (Langkah 2)
activate komplain
return List Ringkasan Komplain / List Kosong (Langkah 2.a)
deactivate komplain

KomplainController -> HalamanPusatPengaduan : Tampilkan daftar ringkasan pengaduan (Langkah 2)
deactivate KomplainController

Admin -> HalamanPusatPengaduan : Memilih laporan yang ingin dilihat detailnya (Langkah 3)

HalamanPusatPengaduan -> KomplainController : ambilDetailKomplain(ID_Komplain)
activate KomplainController

KomplainController -> komplain : Mengambil seluruh data detail laporan (Langkah 5)
activate komplain
return Data Detail Komplain Lengkap
deactivate komplain

KomplainController -> HalamanDetailKomplain : Tampilkan halaman detail laporan (Langkah 6)
deactivate KomplainController
activate HalamanDetailKomplain

HalamanDetailKomplain -> Admin : Melihat dan meninjau detail laporan (Langkah 7)
deactivate HalamanDetailKomplain

' alt Jika Komplain Ditemukan (Main Flow)


' else Jika Daftar Komplain Kosong (Alternative Flow 2.a)
'     note over KomplainController
'         List Komplain Kosong
'     end note
'     KomplainController -> HalamanPusatPengaduan : Tampilkan notifikasi("Tidak ada laporan pengaduan...") (Langkah 3.a)
'     deactivate KomplainController

'     HalamanPusatPengaduan -> Admin : Menerima notifikasi daftar kosong
' end alt
deactivate HalamanPusatPengaduan

@enduml