@startuml SD-UC-K03_HapusBerita
title Sequence Diagram UC-K03: Menghapus Berita (Admin)
skinparam style strictuml

actor Admin
boundary HalamanDaftarBerita
control BeritaController
entity Berita

activate Admin
Admin -> HalamanDaftarBerita : Mengakses halaman "/admin/berita"
activate HalamanDaftarBerita

HalamanDaftarBerita -> Admin : Tampilkan daftar berita

Admin -> HalamanDaftarBerita : Klik "Hapus" (ID_Berita: integer)

HalamanDaftarBerita -> BeritaController : DELETE /admin/berita/{ID_Berita}
activate BeritaController
    
BeritaController -> Berita : deleteById(ID_Berita: integer)
activate Berita
Berita --> BeritaController : deleteStatus: boolean
deactivate Berita
    
BeritaController --> HalamanDaftarBerita : responseSuccess(message: string)
deactivate BeritaController
    
HalamanDaftarBerita -> Admin : Tampilkan notifikasi sukses dan daftar terbaru
deactivate HalamanDaftarBerita
deactivate Admin

@enduml