@startuml SD-UC-K01_MelihatDaftarBeritaAdmin
title Sequence Diagram UC-K01: Melihat Daftar Berita (Admin)
skinparam style strictuml

actor Admin
boundary HalamanDaftarBerita
control BeritaController
entity Berita

activate Admin
Admin -> HalamanDaftarBerita : Mengakses halaman "/admin/berita"
activate HalamanDaftarBerita

HalamanDaftarBerita -> BeritaController : GET /admin/berita
activate BeritaController

BeritaController -> Berita : findAll()
activate Berita
Berita --> BeritaController : List Berita Lengkap: List<Berita>
deactivate Berita

BeritaController --> HalamanDaftarBerita : response(List Berita Lengkap)
deactivate BeritaController
    
HalamanDaftarBerita -> Admin : Melihat dan meninjau daftar berita
deactivate HalamanDaftarBerita
deactivate Admin

@enduml