@startuml SD-UC-K03_HapusBerita
title Sequence Diagram UC-K03: Menghapus Berita (Admin)
skinparam style strictuml

actor Admin
boundary HalamanKelolaBerita
control HapusBeritaController
entity Berita

activate Admin

Admin -> HalamanKelolaBerita : Klik "Hapus"
activate HalamanKelolaBerita

HalamanKelolaBerita -> HapusBeritaController : hapusBerita(id_berita: int)
activate HapusBeritaController

HapusBeritaController -> Berita : Berita::deleteById(id_berita: int)
activate Berita

Berita --> HapusBeritaController : return(true: boolean)
deactivate Berita

HapusBeritaController --> HalamanKelolaBerita : response(data: Array)
deactivate HapusBeritaController

HalamanKelolaBerita -> Admin : Tampilkan notifikasi & daftar berita baru
deactivate HalamanKelolaBerita
deactivate Admin

@enduml