@startuml SD-UC-K01_MelihatDaftarBeritaAdmin
title Sequence Diagram UC-K01: Melihat Daftar Berita (Admin)
skinparam style strictuml

actor Admin
boundary HalamanKelolaBerita
control LihatSemuaBeritaController
entity Berita

Admin -> HalamanKelolaBerita : Mengakses '/admin/berita'
activate HalamanKelolaBerita

HalamanKelolaBerita -> LihatSemuaBeritaController : ambilDaftarBerita()
activate LihatSemuaBeritaController

LihatSemuaBeritaController -> Berita : Berita::all()
activate Berita

Berita --> LihatSemuaBeritaController : return(berita: Array)
deactivate Berita

LihatSemuaBeritaController --> HalamanKelolaBerita : response(berita: Array)
deactivate LihatSemuaBeritaController

HalamanKelolaBerita -> Admin : Tampilkan daftar berita

@enduml