@startuml SD-UC-K01_MelihatDaftarBeritaAdmin
title Sequence Diagram UC-K01: Melihat Daftar Berita (Admin)
skinparam style strictuml

actor Admin
boundary HalamanDaftarBerita
control BeritaController
entity berita

' box "Sistem Manajemen Berita"
'     participant HalamanDaftarBerita
'     participant BeritaController
' end box

activate Admin
Admin -> HalamanDaftarBerita : Mengakses menu "Berita" (Langkah 1)
activate HalamanDaftarBerita

HalamanDaftarBerita -> BeritaController : ambilSemuaBeritaAdmin()
activate BeritaController

BeritaController -> berita : Mengambil daftar seluruh berita (Draft & Terbit) (Langkah 2)
activate berita
return List Berita Lengkap / List Kosong (Langkah 2.a)
deactivate berita

BeritaController -> HalamanDaftarBerita : Tampilkan daftar berita lengkap (Langkah 3)
deactivate BeritaController
    
HalamanDaftarBerita -> Admin : Melihat dan meninjau daftar berita (Langkah 4)

' alt Jika Berita Ditemukan (Main Flow)

' else Jika Daftar Kosong (Alternative Flow 2.a)
'     note over BeritaController
'         List Berita Kosong
'     end note
'     BeritaController -> HalamanDaftarBerita : Tampilkan notifikasi("Belum ada berita yang ditambahkan.") (Langkah 3.a)
'     deactivate BeritaController
    
'     HalamanDaftarBerita -> Admin : Menerima notifikasi daftar kosong (Langkah 4)
' end alt
deactivate HalamanDaftarBerita

@enduml