@startuml SD-UC-K02_TambahBerita
title Sequence Diagram UC-K02: Menambahkan Berita Baru (Admin)
skinparam style strictuml

actor Admin
boundary HalamanDaftarBerita
boundary HalamanFormBerita
control BeritaController
database berita as "berita\n(Database)"

' box "Sistem Manajemen Berita"
'     participant HalamanDaftarBerita
'     participant HalamanFormBerita
'     participant BeritaController
' end box

activate Admin
Admin -> HalamanDaftarBerita : Mengakses halaman daftar berita (Langkah 1)
activate HalamanDaftarBerita

Admin -> HalamanDaftarBerita : Menekan tombol "Tambah Berita" (Langkah 2)
deactivate HalamanDaftarBerita

HalamanFormBerita -> Admin : Tampilkan formulir penambahan berita (Langkah 2)
activate HalamanFormBerita

Admin -> HalamanFormBerita : Mengisi informasi berita (Langkah 3)

Admin -> HalamanFormBerita : Menekan tombol "Terbitkan" (Langkah 4)

HalamanFormBerita -> BeritaController : tambahBerita(Data Berita Baru)
activate BeritaController

BeritaController -> berita : Validasi kelengkapan dan format data (Langkah 5)

BeritaController -> berita : Menyimpan berita baru (Status='Terbit') (Langkah 6.b)
activate berita
return ID_Berita_Baru
deactivate berita
    
BeritaController -> HalamanFormBerita : Tampilkan notifikasi("Berita berhasil diterbitkan") (Langkah 7)

' BeritaController -> HalamanDaftarBerita : Perbarui daftar berita Pembeli
deactivate BeritaController
    
HalamanFormBerita -> Admin : Menerima notifikasi sukses
deactivate HalamanFormBerita

' alt Gagal Validasi (Alternative Flow 5.a)
'     BeritaController -> HalamanFormBerita : Tampilkan notifikasi("Publikasi Gagal: Mohon lengkapi...") (Langkah 6.a)
'     deactivate BeritaController
    
'     HalamanFormBerita -> Admin : Menerima notifikasi gagal
    
'     note over Admin, HalamanFormBerita
'         Memperbaiki data (Langkah 7.a)
'         Kembali ke Langkah 4 (Langkah 7.b)
'     end note
' else Validasi Sukses (Main Flow)

' end alt

@enduml