@startuml UseCaseDiagram_RekayasaSistem

title Use Case Diagram Sistem Informasi

left to right direction

'------------------------------------------------------------------
' AKTOR
'------------------------------------------------------------------
actor Pembeli
actor Admin

'------------------------------------------------------------------
' RELASI PEMBELI
'------------------------------------------------------------------
Pembeli --> (UC-A01 Mendaftar Akun)
Pembeli --> (UC-A02 Masuk ke Akun Pengguna)
Pembeli --> (UC-A03 Memperbarui Data Profil)
Pembeli --> (UC-A04 Mengubah Kata Sandi)

Pembeli --> (UC-B01 Melihat Seluruh Katalog Produk)
Pembeli --> (UC-B02 Mencari Produk)
Pembeli --> (UC-B03 Memfilter Produk)
Pembeli --> (UC-B04 Melihat Detail Produk)

Pembeli --> (UC-C01 Menambahkan Produk ke Keranjang)
Pembeli --> (UC-C02 Melihat Keranjang Belanja)
Pembeli --> (UC-C03 Menghapus Produk Keranjang)
Pembeli --> (UC-C04 Mengubah Kuantitas Produk Keranjang)

Pembeli --> (UC-D01 Melakukan Proses Pemesanan)
Pembeli --> (UC-D02 Melakukan Konfirmasi Pembayaran)
Pembeli --> (UC-E01 Melihat Daftar Seluruh Pesanan)
Pembeli --> (UC-E02 Melihat Detail Pesanan)
Pembeli --> (UC-F01 Mengirim Laporan Pengaduan Produk)

Pembeli --> (UC-G01 Membaca Berita)

'------------------------------------------------------------------
' RELASI ADMIN
'------------------------------------------------------------------
(UC-A02 Masuk ke Akun Pengguna) <-- Admin
' Admin --> (UC-A02 Masuk ke Akun Pengguna as admin)
Admin --> (UC-H01 Melihat Daftar Produk)
Admin --> (UC-H02 Menambahkan Produk)
Admin --> (UC-H03 Menghapus Produk)
Admin --> (UC-H04 Mengarsipkan Produk)
Admin --> (UC-H05 Memperbarui Stok Produk)

Admin --> (UC-I01 Melihat Daftar Pesanan)
Admin --> (UC-I02 Memperbarui Status Pesanan)

Admin --> (UC-J01 Melihat Komplain Produk)

Admin --> (UC-K01 Melihat Daftar Berita)
Admin --> (UC-K02 Menambahkan Berita)
Admin --> (UC-K03 Menghapus Berita)
Admin --> (UC-K04 Memperbarui Berita)

@enduml